name: proof_of_work_verification
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=2.12.0 <=3.10.2'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.1.0
  intl: ^0.19.0
  convert: ^3.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12

flutter:
